title: Data Architect
author: wayne snyder
email: wayne.snyder@mariner-usa.com
description: > # this means to ignore newlines until "baseurl:"
  soundbarrier and in your feed.xml site description.

# social links
twitter_username: #SQLWayne
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
